### ISSUE TITLE
le bot ne fonctionne pas sur mon vps ubuntu

### ISSUE THREAD

**Issue by Gromatou** [alexandre-vl/vinted-fr#1]
```
cardboard@burning-cardboard:~/vintedbot$ npm i && node main.js
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/builders@0.16.0',
npm WARN EBADENGINE   required: { node: '>=16.9.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@0.7.0',
npm WARN EBADENGINE   required: { node: '>=16.9.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sapphire/async-queue@1.5.1',
npm WARN EBADENGINE   required: { node: '>=v14.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sapphire/shapeshift@3.9.5',
npm WARN EBADENGINE   required: { node: '>=v18' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'discord.js@13.17.1',
npm WARN EBADENGINE   required: { node: '>=16.6.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

up to date, audited 77 packages in 660ms

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
file:///home/cardboard/vintedbot/main.js:4
import config from "./config.json" assert { type: "json" };
                                   ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
    ```

**Comment by anthozb3x** [comment]
regarde la versions de node et npm ;)
